import { useMemo, useState, type ReactNode } from "react";
import { CalendarDays, CheckCircle2, CircleAlert, Clock3, Database, GitBranch, Settings2, Sparkles } from "lucide-react";
import { useMigration } from "@/lib/migration/store";
import { analyzeCalendars } from "@/lib/migration/calendar-analysis";
import { AppHeader } from "./AppHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";

export function CalendarAnalysisPage() {
  const analysis = useMigration(s => s.enterpriseAnalysis);
  const result = useMemo(() => analyzeCalendars(analysis), [analysis]);
  const [selectedId, setSelectedId] = useState<string>("");
  const selected = result.candidates.find(c => c.id === selectedId) ?? result.candidates[0];
  const [fiscalStart, setFiscalStart] = useState("detected");
  const [firstDay, setFirstDay] = useState("detected");
  const [culture, setCulture] = useState("en-US");

  const metric = (label:string, value:number, Icon:any) => <Card><CardContent className="pt-5 flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-3"><Icon className="h-5 w-5 text-primary"/></div><div><div className="text-2xl font-bold">{value}</div><div className="text-xs text-muted-foreground">{label}</div></div></CardContent></Card>;
  return <div className="min-h-screen bg-background"><AppHeader/><main className="mx-auto max-w-7xl px-6 py-8 space-y-6">
    <div className="flex items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-primary font-semibold"><CalendarDays className="h-5 w-5"/> Deterministic calendar compiler</div><h1 className="text-3xl font-bold mt-2">Calendar Analysis</h1><p className="text-muted-foreground mt-2 max-w-4xl">Detect Qlik calendar patterns, resolve variables and fact-date dependencies, review fiscal and week semantics, validate generated M and prepare Power BI date-table metadata.</p></div>{selected && <Badge variant="secondary">{selected.kind}</Badge>}</div>
    {!analysis ? <Card><CardContent className="py-12 text-center text-muted-foreground">Upload and analyse a Qlik project first. Calendar candidates will be detected from the consolidated execution graph.</CardContent></Card> : <>
      <div className="grid md:grid-cols-5 gap-4">{metric("Calendars",result.summary.detected,CalendarDays)}{metric("AUTOGENERATE",result.summary.autogenerate,Clock3)}{metric("Fiscal",result.summary.fiscal,Database)}{metric("Role playing",result.summary.rolePlaying,GitBranch)}{metric("Blocking checks",result.summary.blocking,CircleAlert)}</div>
      {result.candidates.length===0 ? <Card><CardContent className="py-10 text-center text-muted-foreground">No calendar candidate was detected. Review the parser inventory or configure a date source manually.</CardContent></Card> : <>
        <div className="flex flex-wrap gap-2">{result.candidates.map(c=><Button key={c.id} variant={selected?.id===c.id?"default":"outline"} onClick={()=>setSelectedId(c.id)}>{c.table}<Badge className="ml-2" variant="secondary">{Math.round(c.confidence*100)}%</Badge></Button>)}</div>
        <Tabs defaultValue="overview"><TabsList className="flex flex-wrap h-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="qlik">Original Qlik logic</TabsTrigger><TabsTrigger value="variables">Resolved variables</TabsTrigger><TabsTrigger value="lineage">Calendar lineage</TabsTrigger><TabsTrigger value="m">Generated M</TabsTrigger><TabsTrigger value="columns">Generated columns</TabsTrigger><TabsTrigger value="sort">Sort configuration</TabsTrigger><TabsTrigger value="relationships">Relationships</TabsTrigger><TabsTrigger value="validation">Validation results</TabsTrigger><TabsTrigger value="repair">AI repair</TabsTrigger></TabsList>
          <TabsContent value="overview"><div className="grid lg:grid-cols-3 gap-4"><Card className="lg:col-span-2"><CardHeader><CardTitle>{selected.table}</CardTitle></CardHeader><CardContent className="grid md:grid-cols-2 gap-4 text-sm"><Info label="Calendar type" value={selected.kind}/><Info label="Date-range source" value={selected.dateRangeSource}/><Info label="Start logic" value={selected.startLogic}/><Info label="End logic" value={selected.endLogic}/><Info label="Fiscal start" value={selected.fiscalStartMonth?`Month ${selected.fiscalStartMonth}`:"Not detected"}/><Info label="Continuity" value={selected.continuous?"Continuous":"Sparse or unknown"}/><div className="md:col-span-2"><b>Detection signals</b><div className="flex gap-2 flex-wrap mt-2">{selected.signals.map(s=><Badge key={s} variant="outline">{s}</Badge>)}</div></div></CardContent></Card><Card><CardHeader><CardTitle className="flex gap-2"><Settings2 className="h-5 w-5"/> Calendar settings</CardTitle></CardHeader><CardContent className="space-y-4"><Setting label="Fiscal start month"><Select value={fiscalStart} onValueChange={setFiscalStart}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="detected">Use detected</SelectItem>{Array.from({length:12},(_,i)=><SelectItem key={i+1} value={String(i+1)}>{new Date(2024,i,1).toLocaleString("en",{month:"long"})}</SelectItem>)}</SelectContent></Select></Setting><Setting label="First day of week"><Select value={firstDay} onValueChange={setFirstDay}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="detected">Use detected/Qlik</SelectItem><SelectItem value="monday">Monday</SelectItem><SelectItem value="sunday">Sunday</SelectItem></SelectContent></Select></Setting><Setting label="Culture"><Input value={culture} onChange={e=>setCulture(e.target.value)}/></Setting><Button className="w-full" variant="outline">Save override proposal</Button></CardContent></Card></div></TabsContent>
          <TabsContent value="qlik"><CodeCard title="Original consolidated Qlik calendar logic" code={selected.qlikScript}/></TabsContent>
          <TabsContent value="variables"><Card><CardContent className="pt-6 space-y-3">{result.variables.length?result.variables.map(v=><div key={v.name} className="rounded-lg border p-3 grid md:grid-cols-4 gap-2 text-sm"><b>{v.name}</b><code className="md:col-span-2 break-all">{v.expression}</code><Badge variant={v.status==="resolved"?"default":"outline"}>{v.status} · {Math.round(v.confidence*100)}%</Badge>{v.resolvedValue&&<div className="md:col-span-4 text-emerald-600">Resolved: {v.resolvedValue}</div>}</div>):<p className="text-muted-foreground">No calendar-related variables were found.</p>}</CardContent></Card></TabsContent>
          <TabsContent value="lineage"><Card><CardContent className="pt-6 space-y-3"><Line label="Source" value={selected.dateRangeSource}/><Line label="Dependencies" value={selected.factDependencies.join(" → ")||"No external dependency; generated sequence"}/><Line label="Calendar" value={selected.table}/><Line label="Power BI output" value="Date table + sort metadata + validated relationships"/></CardContent></Card></TabsContent>
          <TabsContent value="m"><CodeCard title="Generated Power Query M" code={selected.generatedM||"M has not yet been generated for this calendar. Regenerate Power Query after resolving the calendar plan."}/></TabsContent>
          <TabsContent value="columns"><Card><CardContent className="pt-6 flex flex-wrap gap-2">{selected.generatedColumns.map(c=><Badge key={c} variant="outline">{c}</Badge>)}</CardContent></Card></TabsContent>
          <TabsContent value="sort"><Card><CardContent className="pt-6 space-y-2 text-sm"><Line label="Month" value="MonthNumber"/><Line label="Quarter" value="QuarterNumber"/><Line label="WeekDay" value="WeekDayNumber"/><Line label="MonthYear" value="MonthYearSort"/><Line label="WeekYear" value="WeekYearSort"/><p className="text-muted-foreground pt-2">Only mappings supported by generated columns are written to the semantic model. Missing sort columns are generated as Power BI enhancements.</p></CardContent></Card></TabsContent>
          <TabsContent value="relationships"><Card><CardContent className="pt-6 space-y-3">{selected.factDependencies.length?selected.factDependencies.map(d=><div key={d} className="rounded-lg border p-3 text-sm"><b>{selected.table}[Date]</b> → {d} <Badge className="ml-2" variant="outline">validate key</Badge></div>):<p className="text-muted-foreground">No fact dependency was resolved. The source resolver will score eligible date fields before proposing a relationship.</p>}</CardContent></Card></TabsContent>
          <TabsContent value="validation"><Card><CardContent className="pt-6 space-y-3">{selected.validation.map(v=><div key={v.name} className="flex items-start gap-3 rounded-lg border p-3">{v.status==="pass"?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<CircleAlert className={`h-5 w-5 ${v.status==="error"?"text-red-600":"text-amber-600"}`}/>}<div><b>{v.name}</b><p className="text-sm text-muted-foreground">{v.detail}</p></div></div>)}</CardContent></Card></TabsContent>
          <TabsContent value="repair"><Card><CardHeader><CardTitle className="flex gap-2"><Sparkles className="h-5 w-5"/> Calendar AI repair plan</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>1. Identify the exact generation pattern and source operations.</p><p>2. Resolve literal, variable, Peek, Min/Max or fact-field date bounds.</p><p>3. Compile AUTOGENERATE/WHILE/IterNo to List.Dates, List.DateTimes or List.Generate.</p><p>4. Convert deterministic functions such as WeekDay and Right without treating function names as fields.</p><p>5. Repair datatypes and create display/sort pairs.</p><p>6. Revalidate M syntax, date-key uniqueness, continuity and relationships.</p>{selected.warnings.map(w=><div key={w} className="rounded-lg border border-amber-300 bg-amber-50/50 p-3">{w}</div>)}<Button>Generate reviewable repair proposal</Button></CardContent></Card></TabsContent>
        </Tabs>
      </>}
    </>}
  </main></div>;
}
function Info({label,value}:{label:string,value:string}){return <div><b>{label}</b><p className="text-muted-foreground break-words">{value}</p></div>}
function Setting({label,children}:{label:string,children:ReactNode}){return <div className="space-y-1"><div className="text-xs font-medium">{label}</div>{children}</div>}
function CodeCard({title,code}:{title:string,code:string}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><pre className="max-h-[560px] overflow-auto rounded-lg bg-slate-950 text-slate-100 p-4 text-xs whitespace-pre-wrap">{code}</pre></CardContent></Card>}
function Line({label,value}:{label:string,value:string}){return <div className="grid grid-cols-[160px_1fr] gap-3 rounded-lg border p-3"><b>{label}</b><span className="text-muted-foreground break-all">{value}</span></div>}
