/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSemanticModelRouteImport } from './routes/app/semantic-model'
import { Route as AppReportDesignerRouteImport } from './routes/app/report-designer'
import { Route as AppRelationshipsRouteImport } from './routes/app/relationships'
import { Route as AppQvwAnalysisRouteImport } from './routes/app/qvw-analysis'
import { Route as AppPowerbiModelRouteImport } from './routes/app/powerbi-model'
import { Route as AppPowerQueryRouteImport } from './routes/app/power-query'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppInstructionsRouteImport } from './routes/app/instructions'
import { Route as AppExpressionConversionRouteImport } from './routes/app/expression-conversion'
import { Route as AppDaxMeasuresRouteImport } from './routes/app/dax-measures'
import { Route as AppCalendarAnalysisRouteImport } from './routes/app/calendar-analysis'
import { Route as AppAnalysisRouteImport } from './routes/app/analysis'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSemanticModelRoute = AppSemanticModelRouteImport.update({
  id: '/semantic-model',
  path: '/semantic-model',
  getParentRoute: () => AppRoute,
} as any)
const AppReportDesignerRoute = AppReportDesignerRouteImport.update({
  id: '/report-designer',
  path: '/report-designer',
  getParentRoute: () => AppRoute,
} as any)
const AppRelationshipsRoute = AppRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => AppRoute,
} as any)
const AppQvwAnalysisRoute = AppQvwAnalysisRouteImport.update({
  id: '/qvw-analysis',
  path: '/qvw-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppPowerbiModelRoute = AppPowerbiModelRouteImport.update({
  id: '/powerbi-model',
  path: '/powerbi-model',
  getParentRoute: () => AppRoute,
} as any)
const AppPowerQueryRoute = AppPowerQueryRouteImport.update({
  id: '/power-query',
  path: '/power-query',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInstructionsRoute = AppInstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => AppRoute,
} as any)
const AppExpressionConversionRoute = AppExpressionConversionRouteImport.update({
  id: '/expression-conversion',
  path: '/expression-conversion',
  getParentRoute: () => AppRoute,
} as any)
const AppDaxMeasuresRoute = AppDaxMeasuresRouteImport.update({
  id: '/dax-measures',
  path: '/dax-measures',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarAnalysisRoute = AppCalendarAnalysisRouteImport.update({
  id: '/calendar-analysis',
  path: '/calendar-analysis',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/calendar-analysis': typeof AppCalendarAnalysisRoute
  '/app/dax-measures': typeof AppDaxMeasuresRoute
  '/app/expression-conversion': typeof AppExpressionConversionRoute
  '/app/instructions': typeof AppInstructionsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/power-query': typeof AppPowerQueryRoute
  '/app/powerbi-model': typeof AppPowerbiModelRoute
  '/app/qvw-analysis': typeof AppQvwAnalysisRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app/report-designer': typeof AppReportDesignerRoute
  '/app/semantic-model': typeof AppSemanticModelRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/calendar-analysis': typeof AppCalendarAnalysisRoute
  '/app/dax-measures': typeof AppDaxMeasuresRoute
  '/app/expression-conversion': typeof AppExpressionConversionRoute
  '/app/instructions': typeof AppInstructionsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/power-query': typeof AppPowerQueryRoute
  '/app/powerbi-model': typeof AppPowerbiModelRoute
  '/app/qvw-analysis': typeof AppQvwAnalysisRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app/report-designer': typeof AppReportDesignerRoute
  '/app/semantic-model': typeof AppSemanticModelRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/app/analysis': typeof AppAnalysisRoute
  '/app/calendar-analysis': typeof AppCalendarAnalysisRoute
  '/app/dax-measures': typeof AppDaxMeasuresRoute
  '/app/expression-conversion': typeof AppExpressionConversionRoute
  '/app/instructions': typeof AppInstructionsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/power-query': typeof AppPowerQueryRoute
  '/app/powerbi-model': typeof AppPowerbiModelRoute
  '/app/qvw-analysis': typeof AppQvwAnalysisRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app/report-designer': typeof AppReportDesignerRoute
  '/app/semantic-model': typeof AppSemanticModelRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/app/analysis'
    | '/app/calendar-analysis'
    | '/app/dax-measures'
    | '/app/expression-conversion'
    | '/app/instructions'
    | '/app/logs'
    | '/app/power-query'
    | '/app/powerbi-model'
    | '/app/qvw-analysis'
    | '/app/relationships'
    | '/app/report-designer'
    | '/app/semantic-model'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/app/analysis'
    | '/app/calendar-analysis'
    | '/app/dax-measures'
    | '/app/expression-conversion'
    | '/app/instructions'
    | '/app/logs'
    | '/app/power-query'
    | '/app/powerbi-model'
    | '/app/qvw-analysis'
    | '/app/relationships'
    | '/app/report-designer'
    | '/app/semantic-model'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/app/analysis'
    | '/app/calendar-analysis'
    | '/app/dax-measures'
    | '/app/expression-conversion'
    | '/app/instructions'
    | '/app/logs'
    | '/app/power-query'
    | '/app/powerbi-model'
    | '/app/qvw-analysis'
    | '/app/relationships'
    | '/app/report-designer'
    | '/app/semantic-model'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/semantic-model': {
      id: '/app/semantic-model'
      path: '/semantic-model'
      fullPath: '/app/semantic-model'
      preLoaderRoute: typeof AppSemanticModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report-designer': {
      id: '/app/report-designer'
      path: '/report-designer'
      fullPath: '/app/report-designer'
      preLoaderRoute: typeof AppReportDesignerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relationships': {
      id: '/app/relationships'
      path: '/relationships'
      fullPath: '/app/relationships'
      preLoaderRoute: typeof AppRelationshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qvw-analysis': {
      id: '/app/qvw-analysis'
      path: '/qvw-analysis'
      fullPath: '/app/qvw-analysis'
      preLoaderRoute: typeof AppQvwAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/powerbi-model': {
      id: '/app/powerbi-model'
      path: '/powerbi-model'
      fullPath: '/app/powerbi-model'
      preLoaderRoute: typeof AppPowerbiModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/power-query': {
      id: '/app/power-query'
      path: '/power-query'
      fullPath: '/app/power-query'
      preLoaderRoute: typeof AppPowerQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instructions': {
      id: '/app/instructions'
      path: '/instructions'
      fullPath: '/app/instructions'
      preLoaderRoute: typeof AppInstructionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expression-conversion': {
      id: '/app/expression-conversion'
      path: '/expression-conversion'
      fullPath: '/app/expression-conversion'
      preLoaderRoute: typeof AppExpressionConversionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dax-measures': {
      id: '/app/dax-measures'
      path: '/dax-measures'
      fullPath: '/app/dax-measures'
      preLoaderRoute: typeof AppDaxMeasuresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar-analysis': {
      id: '/app/calendar-analysis'
      path: '/calendar-analysis'
      fullPath: '/app/calendar-analysis'
      preLoaderRoute: typeof AppCalendarAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analysis': {
      id: '/app/analysis'
      path: '/analysis'
      fullPath: '/app/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppCalendarAnalysisRoute: typeof AppCalendarAnalysisRoute
  AppDaxMeasuresRoute: typeof AppDaxMeasuresRoute
  AppExpressionConversionRoute: typeof AppExpressionConversionRoute
  AppInstructionsRoute: typeof AppInstructionsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppPowerQueryRoute: typeof AppPowerQueryRoute
  AppPowerbiModelRoute: typeof AppPowerbiModelRoute
  AppQvwAnalysisRoute: typeof AppQvwAnalysisRoute
  AppRelationshipsRoute: typeof AppRelationshipsRoute
  AppReportDesignerRoute: typeof AppReportDesignerRoute
  AppSemanticModelRoute: typeof AppSemanticModelRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysisRoute: AppAnalysisRoute,
  AppCalendarAnalysisRoute: AppCalendarAnalysisRoute,
  AppDaxMeasuresRoute: AppDaxMeasuresRoute,
  AppExpressionConversionRoute: AppExpressionConversionRoute,
  AppInstructionsRoute: AppInstructionsRoute,
  AppLogsRoute: AppLogsRoute,
  AppPowerQueryRoute: AppPowerQueryRoute,
  AppPowerbiModelRoute: AppPowerbiModelRoute,
  AppQvwAnalysisRoute: AppQvwAnalysisRoute,
  AppRelationshipsRoute: AppRelationshipsRoute,
  AppReportDesignerRoute: AppReportDesignerRoute,
  AppSemanticModelRoute: AppSemanticModelRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
