import type { TmdlDiagnostic, TomColumn, TomDatabaseSpec } from "./TomModelTypes";

function key(value: string): string { return value.trim().toLocaleLowerCase(); }
function diagnostic(code: string, severity: TmdlDiagnostic["severity"], objectPath: string, message: string, recommendation: string): TmdlDiagnostic {
  return { code, severity, objectPath, message, recommendation };
}

function qualifiedDaxReferences(expression: string): Array<{ table: string; object: string }> {
  return [...expression.matchAll(/(?:'((?:[^']|'')+)'|([A-Za-z_][A-Za-z0-9_ ]*))\s*\[([^\]]+)\]/g)]
    .map((match) => ({
      table: (match[1] || match[2] || "").replace(/''/g, "'").trim(),
      object: (match[3] || "").trim(),
    }))
    .filter((item) => item.table && item.object);
}

export function validateTomModelSpec(spec: TomDatabaseSpec): TmdlDiagnostic[] {
  const diagnostics: TmdlDiagnostic[] = [];
  if (!spec.name.trim()) diagnostics.push(diagnostic("TMDL_DATABASE_NAME_MISSING", "blocking-error", "database", "Database name is empty.", "Provide a non-empty project name."));
  if (spec.compatibilityLevel < 1200) diagnostics.push(diagnostic("TMDL_COMPATIBILITY_LEVEL", "blocking-error", "database", `Compatibility level ${spec.compatibilityLevel} does not support TMDL.`, "Use compatibility level 1604 or a compatible level supported by the target Power BI Desktop."));
  if (!spec.model.tables.length) diagnostics.push(diagnostic("TMDL_NO_TABLES", "blocking-error", "model", "The semantic model contains no tables.", "Generate at least one imported or calculated table before export."));

  const tableNames = new Set<string>();
  const globalMeasureNames = new Map<string, string>();
  for (const table of spec.model.tables) {
    const tablePath = `model.tables[${table.name}]`;
    if (!table.name.trim()) diagnostics.push(diagnostic("TMDL_TABLE_NAME_MISSING", "blocking-error", tablePath, "A table has an empty name.", "Assign a unique table name."));
    if (tableNames.has(key(table.name))) diagnostics.push(diagnostic("TMDL_DUPLICATE_TABLE", "blocking-error", tablePath, `Duplicate table name '${table.name}'.`, "Rename one of the tables."));
    tableNames.add(key(table.name));
    if (!table.partitions.length) diagnostics.push(diagnostic("TMDL_TABLE_PARTITION_MISSING", "blocking-error", tablePath, `Table '${table.name}' has no partition.`, "Create an M or calculated partition."));

    const columnNames = new Set<string>();
    const keyColumns = table.columns.filter((column) => column.isKey);
    if (keyColumns.length > 1) diagnostics.push(diagnostic("TMDL_MULTIPLE_TABLE_KEYS", "blocking-error", tablePath, `Table '${table.name}' has ${keyColumns.length} columns with isKey enabled.`, "Select one Row Identifier in the Power BI Model page, or use None for a fact table without a verified unique row ID."));
    for (const column of table.columns) {
      const path = `${tablePath}.columns[${column.name}]`;
      if (!column.name.trim()) diagnostics.push(diagnostic("TMDL_COLUMN_NAME_MISSING", "blocking-error", path, "A column has an empty name.", "Assign a non-empty column name."));
      if (columnNames.has(key(column.name))) diagnostics.push(diagnostic("TMDL_DUPLICATE_COLUMN", "blocking-error", path, `Duplicate column '${column.name}' in table '${table.name}'.`, "Rename or remove the duplicate column."));
      columnNames.add(key(column.name));
      validateColumn(column, path, diagnostics);
    }

    for (const measure of table.measures) {
      const path = `${tablePath}.measures[${measure.name}]`;
      const measureNameKey = key(measure.name);
      const expressionKey = measure.expression.replace(/\/\/.*$/gm, "").replace(/\s+/g, "").toLocaleLowerCase();
      if (!measure.expression.trim()) diagnostics.push(diagnostic("TMDL_MEASURE_EXPRESSION_MISSING", "blocking-error", path, `Measure '${measure.name}' has no DAX expression.`, "Provide a valid DAX expression or exclude the measure."));
      const existingMeasurePath = globalMeasureNames.get(measureNameKey);
      if (existingMeasurePath) diagnostics.push(diagnostic("TMDL_DUPLICATE_MEASURE", "blocking-error", path, `Measure '${measure.name}' duplicates a model measure already defined at ${existingMeasurePath}.`, "Use one model-wide unique measure name."));
      else globalMeasureNames.set(measureNameKey, path);
      if (columnNames.has(measureNameKey)) diagnostics.push(diagnostic("TMDL_COLUMN_MEASURE_COLLISION", "blocking-error", path, `Measure '${measure.name}' has the same name as a column in '${table.name}'.`, "Use the collision-safe name generated by the migration application."));
      if (!measure.displayFolder?.trim()) diagnostics.push(diagnostic("TMDL_MEASURE_FOLDER_MISSING", "blocking-error", path, `Measure '${measure.name}' has no display folder.`, "Assign every generated measure to a display folder."));
      if (/\b(?:RGB|ARGB|ColorMix1|ColorMix2|ColorMapJet|ColorMapHue)\s*\(/i.test(measure.expression)) {
        diagnostics.push(diagnostic("TMDL_INVALID_QLIK_COLOR_FUNCTION", "blocking-error", path, `Measure '${measure.name}' still contains a Qlik-only colour function.`, "Regenerate the expression so it returns a Power BI-compatible hexadecimal colour text value."));
      }
      for (const reference of qualifiedDaxReferences(measure.expression)) {
        const referencedTable = spec.model.tables.find((candidate) => key(candidate.name) === key(reference.table));
        const objectExists = referencedTable && (
          referencedTable.columns.some((column) => key(column.name) === key(reference.object))
          || referencedTable.measures.some((candidate) => key(candidate.name) === key(reference.object))
        );
        if (!objectExists) {
          diagnostics.push(diagnostic("TMDL_DAX_DEPENDENCY_MISSING", "blocking-error", path, `Measure '${measure.name}' references missing object '${reference.table}[${reference.object}]'.`, "Map the Qlik field to an exported Power BI column or exclude the measure until its dependency is resolved."));
        }
      }
      // Identical DAX expressions are valid in TOM/TMDL. They can occur when
      // distinct Qlik variables or business measures intentionally share a
      // scalar value. Measure-name uniqueness remains enforced model-wide;
      // expression duplication is informational and must not block export.
    }

    for (const hierarchy of table.hierarchies) {
      for (const level of hierarchy.levels) {
        if (!columnNames.has(key(level.column))) diagnostics.push(diagnostic("TMDL_HIERARCHY_COLUMN_MISSING", "blocking-error", `${tablePath}.hierarchies[${hierarchy.name}]`, `Hierarchy level '${level.name}' references missing column '${level.column}'.`, "Select an existing table column for the hierarchy level."));
      }
    }
  }

  const relationshipNames = new Set<string>();
  for (const relationship of spec.model.relationships) {
    const path = `model.relationships[${relationship.name}]`;
    if (relationshipNames.has(key(relationship.name))) diagnostics.push(diagnostic("TMDL_DUPLICATE_RELATIONSHIP", "blocking-error", path, `Duplicate relationship name '${relationship.name}'.`, "Generate a unique relationship identifier."));
    relationshipNames.add(key(relationship.name));
    const fromTable = spec.model.tables.find((table) => key(table.name) === key(relationship.fromTable));
    const toTable = spec.model.tables.find((table) => key(table.name) === key(relationship.toTable));
    if (!fromTable || !toTable) {
      diagnostics.push(diagnostic("TMDL_RELATIONSHIP_TABLE_MISSING", "blocking-error", path, "Relationship references a table that is not exported.", "Include both relationship tables or remove the relationship."));
      continue;
    }
    if (!fromTable.columns.some((column) => key(column.name) === key(relationship.fromColumn)) || !toTable.columns.some((column) => key(column.name) === key(relationship.toColumn))) {
      diagnostics.push(diagnostic("TMDL_RELATIONSHIP_COLUMN_MISSING", "blocking-error", path, "Relationship references a column that is not exported.", "Select valid relationship columns."));
    }
    if (relationship.fromTable === relationship.toTable && relationship.fromColumn === relationship.toColumn) diagnostics.push(diagnostic("TMDL_SELF_RELATIONSHIP", "blocking-error", path, "A relationship cannot connect a column to itself.", "Select different endpoints."));
  }
  return diagnostics;
}

function validateColumn(column: TomColumn, path: string, diagnostics: TmdlDiagnostic[]): void {
  if (column.kind === "data") {
    if (!column.sourceColumn.trim()) diagnostics.push(diagnostic("TMDL_SOURCE_COLUMN_MISSING", "blocking-error", path, `Source column '${column.name}' has no sourceColumn.`, "Provide the physical source column name."));
    if ((column as unknown as { expression?: string }).expression) diagnostics.push(diagnostic("TMDL_SOURCE_COLUMN_HAS_EXPRESSION", "blocking-error", path, `Source column '${column.name}' incorrectly contains an expression.`, "Classify it as a calculated column or remove the expression."));
  } else {
    if (!column.expression.trim()) diagnostics.push(diagnostic("TMDL_CALCULATED_COLUMN_EXPRESSION_MISSING", "blocking-error", path, `Calculated column '${column.name}' has no expression.`, "Provide a row-context DAX expression."));
    if ((column as unknown as { sourceColumn?: string }).sourceColumn) diagnostics.push(diagnostic("TMDL_CALCULATED_COLUMN_HAS_SOURCE", "blocking-error", path, `Calculated column '${column.name}' incorrectly contains sourceColumn.`, "Remove sourceColumn from calculated columns."));
  }
}

export function hasBlockingTmdlDiagnostics(diagnostics: TmdlDiagnostic[]): boolean {
  return diagnostics.some((item) => item.severity === "blocking-error");
}
